### ISSUE TITLE
Dev Google Drive Integration

### ISSUE THREAD

**Issue by chrisputnam9** [chrisputnam9/faces#10]
**Todo:**
- [x] Finish updates to DataSyncable
- [x] Test and debug all data points are syncing.  Back up, sync, load from chromium.
    - [x] Make sure 'updated_at' changes when data changes - all types of data
    - [x] Switch up how dataSyncable works to have it include the full structure
    - [x] After sync success, get button and messaging working right
    - [x] Try a bit more to get Caddy working for FF & Chromium.
    - [x] Worst-case, push live and test there OR set up separate Chrome profile for testing
    - [x] remote_updated_after_sync - logic not working properly
    - [x] Keep updated_at synced up to local storage so it can persist
    - [x] Show sync success properly
- [x] Set up auto-sync - sync to GDrive periodically, when idle, after changes...

**Reference:**
Refer to [quixer-dev project](https://console.cloud.google.com/apis/credentials?project=quixer-dev)
[Faces DEV Project](https://console.cloud.google.com/apis/credentials?project=faces-dev-430211)
[Drive App Files](https://drive.google.com/drive/settings)
[Third-Party Apps](https://myaccount.google.com/connections)

**Completed:**
- [x] Set up new GCP Project
- [x] Set up Oauth Consent Details
- [x] Set up Credentials
- [x] Get caddy proxy running for local development
- [x] Have login immediately reflected with buttons
- [x] Save email (optional)
- [x] Update "config" to "data"
  - [x] perl -pi -w -e 's/CONFIG_SYNC_SAVE_STATE/DATA_SYNC_SAVE_STATE/g;' ./**/*.ts
- [x] Update dataSyncable whenever any data changes
- [x] Debug console errors
- [x] Find data files - readData:, findData:
- [x] Create data files if none
- [x] Read data files if present - Debug, not working....
- [x] Merge data files with local data - maybe just keep most recent?
- [x] Figure out why 'sync' local store is behaving so oddly... seems like it's getting updated by something, but nothing is being logged and local storage isn't updating...
    - [x] Direct object mutation is likely the problem - may need to figure out how I can address this...
